### ISSUE TITLE
Getting Error Sass::SyntaxError - Undefined variable: "$filter-field-seperator-width"

### ISSUE THREAD

**Issue by Asnadatta** [dkniffin/active_material#26]
I am using activeadmin (1.0.0). I found active_material pretty simple using in my new project but when I try it on my existing project it crashed let me share logs.
**sass::SyntaxError - Undefined variable: "$filter-field-seperator-width".:**
sass (3.4.19) lib/sass/script/tree/variable.rb:49:in _perform' sass (3.4.19) lib/sass/script/tree/node.rb:50:inperform'
sass (3.4.19) lib/sass/tree/visitors/perform.rb:395:in visit_prop' sass (3.4.19) lib/sass/tree/visitors/base.rb:36:invisit'
sass (3.4.19) lib/sass/tree/visitors/perform.rb:158:in block in visit' sass (3.4.19) lib/sass/stack.rb:79:inblock in with_base'
sass (3.4.19) lib/sass/stack.rb:115:in with_frame' sass (3.4.19) lib/sass/stack.rb:79:inwith_base'
sass (3.4.19) lib/sass/tree/visitors/perform.rb:158:in visit' sass (3.4.19) lib/sass/tree/visitors/perform.rb:431:inblock (2 levels) in visit_rule'
sass (3.4.19) lib/sass/tree/visitors/perform.rb:431:in block in visit_rule' sass (3.4.19) lib/sass/tree/visitors/perform.rb:179:inwith_environment'
sass (3.4.19) lib/sass/tree/visitors/perform.rb:429:in visit_rule' sass (3.4.19) lib/sass/tree/visitors/base.rb:36:invisit'
sass (3.4.19) lib/sass/tree/visitors/perform.rb:158:in block in visit' sass (3.4.19) lib/sass/stack.rb:79:inblock in with_base'
sass (3.4.19) lib/sass/stack.rb:115:in with_frame' sass (3.4.19) lib/sass/stack.rb:79:inwith_base'
sass (3.4.19) lib/sass/tree/visitors/perform.rb:158:in visit' sass (3.4.19) lib/sass/tree/visitors/perform.rb:431:inblock (2 levels) in visit_rule'
sass (3.4.19) lib/sass/tree/visitors/perform.rb:431:in block in visit_rule' sass (3.4.19) lib/sass/tree/visitors/perform.rb:179:inwith_environment'
sass (3.4.19) lib/sass/tree/visitors/perform.rb:429:in visit_rule' sass (3.4.19) lib/sass/tree/visitors/base.rb:36:invisit'
sass (3.4.19) lib/sass/tree/visitors/perform.rb:158:in block in visit' sass (3.4.19) lib/sass/stack.rb:79:inblock in with_base'
sass (3.4.19) lib/sass/stack.rb:115:in with_frame' sass (3.4.19) lib/sass/stack.rb:79:inwith_base'
sass (3.4.19) lib/sass/tree/visitors/perform.rb:158:in visit' sass (3.4.19) lib/sass/tree/visitors/perform.rb:431:inblock (2 levels) in visit_rule'
sass (3.4.19) lib/sass/tree/visitors/perform.rb:431:in block in visit_rule' sass (3.4.19) lib/sass/tree/visitors/perform.rb:179:inwith_environment'
sass (3.4.19) lib/sass/tree/visitors/perform.rb:429:in visit_rule' sass (3.4.19) lib/sass/tree/visitors/base.rb:36:invisit'
sass (3.4.19) lib/sass/tree/visitors/perform.rb:158:in block in visit' sass (3.4.19) lib/sass/stack.rb:79:inblock in with_base'
sass (3.4.19) lib/sass/stack.rb:115:in with_frame' sass (3.4.19) lib/sass/stack.rb:79:inwith_base'
sass (3.4.19) lib/sass/tree/visitors/perform.rb:158:in visit' sass (3.4.19) lib/sass/tree/visitors/perform.rb:431:inblock (2 levels) in visit_rule'
sass (3.4.19) lib/sass/tree/visitors/perform.rb:431:in block in visit_rule' sass (3.4.19) lib/sass/tree/visitors/perform.rb:179:inwith_environment'
sass (3.4.19) lib/sass/tree/visitors/perform.rb:429:in visit_rule' sass (3.4.19) lib/sass/tree/visitors/base.rb:36:invisit'
sass (3.4.19) lib/sass/tree/visitors/perform.rb:158:in block in visit' sass (3.4.19) lib/sass/stack.rb:79:inblock in with_base'
sass (3.4.19) lib/sass/stack.rb:115:in with_frame' sass (3.4.19) lib/sass/stack.rb:79:inwith_base'
sass (3.4.19) lib/sass/tree/visitors/perform.rb:158:in visit' sass (3.4.19) lib/sass/tree/visitors/perform.rb:326:inblock (2 levels) in visit_import'
sass (3.4.19) lib/sass/tree/visitors/perform.rb:326:in block in visit_import' sass (3.4.19) lib/sass/stack.rb:88:inblock in with_import'
sass (3.4.19) lib/sass/stack.rb:115:in with_frame' sass (3.4.19) lib/sass/stack.rb:88:inwith_import'
sass (3.4.19) lib/sass/tree/visitors/perform.rb:323:in visit_import' sass (3.4.19) lib/sass/tree/visitors/base.rb:36:invisit'
sass (3.4.19) lib/sass/tree/visitors/perform.rb:158:in block in visit' sass (3.4.19) lib/sass/stack.rb:79:inblock in with_base'
sass (3.4.19) lib/sass/stack.rb:115:in with_frame' sass (3.4.19) lib/sass/stack.rb:79:inwith_base'
sass (3.4.19) lib/sass/tree/visitors/perform.rb:158:in visit' sass (3.4.19) lib/sass/tree/visitors/base.rb:52:inblock in visit_children'
sass (3.4.19) lib/sass/tree/visitors/base.rb:52:in visit_children' sass (3.4.19) lib/sass/tree/visitors/perform.rb:167:inblock in visit_children'
sass (3.4.19) lib/sass/tree/visitors/perform.rb:179:in with_environment' sass (3.4.19) lib/sass/tree/visitors/perform.rb:166:invisit_children'
sass (3.4.19) lib/sass/tree/visitors/base.rb:36:in block in visit' sass (3.4.19) lib/sass/tree/visitors/perform.rb:186:invisit_root'
sass (3.4.19) lib/sass/tree/visitors/base.rb:36:in visit' sass (3.4.19) lib/sass/tree/visitors/perform.rb:157:invisit'
sass (3.4.19) lib/sass/tree/visitors/perform.rb:8:in visit' sass (3.4.19) lib/sass/tree/root_node.rb:36:incss_tree'
sass (3.4.19) lib/sass/tree/root_node.rb:20:in render' sass (3.4.19) lib/sass/engine.rb:278:inrender'
compass-rails (3.0.0) lib/compass-rails/patches/sass_importer.rb:48:in evaluate' tilt (2.0.1) lib/tilt/template.rb:96:inrender'
sprockets (3.5.2) lib/sprockets/legacy_tilt_processor.rb:25:in call' sprockets (3.5.2) lib/sprockets/processor_utils.rb:75:incall_processor'
sprockets (3.5.2) lib/sprockets/processor_utils.rb:57:in block in call_processors' sprockets (3.5.2) lib/sprockets/processor_utils.rb:56:incall_processors'
sprockets (3.5.2) lib/sprockets/loader.rb:134:in load_from_unloaded' sprockets (3.5.2) lib/sprockets/loader.rb:60:inblock in load'
sprockets (3.5.2) lib/sprockets/loader.rb:318:in fetch_asset_from_dependency_cache' sprockets (3.5.2) lib/sprockets/loader.rb:44:inload'
sprockets (3.5.2) lib/sprockets/cached_environment.rb:20:in block in initialize' sprockets (3.5.2) lib/sprockets/cached_environment.rb:47:inload'
sprockets (3.5.2) lib/sprockets/bundle.rb:23:in block in call' sprockets (3.5.2) lib/sprockets/utils.rb:183:indfs'
sprockets (3.5.2) lib/sprockets/bundle.rb:24:in call' sprockets (3.5.2) lib/sprockets/processor_utils.rb:75:incall_processor'
sprockets (3.5.2) lib/sprockets/processor_utils.rb:57:in block in call_processors' sprockets (3.5.2) lib/sprockets/processor_utils.rb:56:incall_processors'
sprockets (3.5.2) lib/sprockets/loader.rb:134:in load_from_unloaded' sprockets (3.5.2) lib/sprockets/loader.rb:60:inblock in load'
sprockets (3.5.2) lib/sprockets/loader.rb:318:in fetch_asset_from_dependency_cache' sprockets (3.5.2) lib/sprockets/loader.rb:44:inload'
sprockets (3.5.2) lib/sprockets/cached_environment.rb:20:in block in initialize' sprockets (3.5.2) lib/sprockets/cached_environment.rb:47:inload'
sprockets (3.5.2) lib/sprockets/base.rb:66:in find_asset' sprockets (3.5.2) lib/sprockets/environment.rb:30:infind_asset'
sprockets (3.5.2) lib/sprockets/base.rb:92:in []' sprockets-rails (2.3.3) lib/sprockets/rails/helper.rb:230:inlookup_asset_for_path'
sprockets-rails (2.3.3) lib/sprockets/rails/helper.rb:190:in check_errors_for' sprockets-rails (2.3.3) lib/sprockets/rails/helper.rb:159:inblock in stylesheet_link_tag'
sprockets-rails (2.3.3) lib/sprockets/rails/helper.rb:158:in `stylesheet_link_tag'

**Comment by nhunzaker** [comment]
Yikes! I wonder what's up. From a quick search, I'm unable to find that variable, however it's hard to do a search from prior commits.  What happens if you pull in the latest version of active_material (1.4.1):

https://github.com/vigetlabs/active_material/releases/tag/v1.4.1

**Comment by nhunzaker** [comment]
Okay. Got it. It looks like this is from active_admin:

https://github.com/brentvatne/active_admin/blob/master/app/assets/stylesheets/active_admin/_forms.css.scss#L212

I'm curious if there's a partial compilation bug here, what happens if you clear the asset cache like this:

```
rake tmp:clear
```

?

**Comment by kotlyarenko-d** [comment]
Hello.
Got the same error...
activeadmin (1.0.0.pre2)
active_material (1.4.1)

`rake tmp:clear ` did not help...

**Comment by nhunzaker** [comment]
This variable is not defined within active_material. It's hard for me to track this down without knowing what your active_admin.scss stylesheet looks like. 

Do you have code/gems in your app that rely on active_admin?

What happens if you directly import active_admin/_forms (https://github.com/activeadmin/activeadmin/blob/5b711b6e22230e6e28be2a9d7367e9423d5dcc25/app/assets/stylesheets/active_admin/_forms.scss) like:

```
@import "active_admin/forms";
```

**Comment by megatux** [comment]
> What happens if you directly import active_admin/_forms (https://github.com/activeadmin/activeadmin/blob/5b711b6e22230e6e28be2a9d7367e9423d5dcc25/app/assets/stylesheets/active_admin/_forms.scss) like:
> 
> ```
> @import "active_admin/forms";
> ```

That seems to fix the problem here :+1: :
```
// @import "active_admin/base";
@import "active_admin/_forms.scss";
@import "active_material";
```
