### ISSUE TITLE
Font weights aren't variables

### ISSUE THREAD

**Issue by ShaunSpringer** [dkniffin/active_material#27]
Font weights are scattered all over the various components, atoms, etc. These should be variables (or mixins). It makes it very difficult to use a thin font or custom weights!

**Comment by nhunzaker** [comment]
Ack! They aren't! Just curious, what parts are you customizing? I'd like to figure out if there are other variables we can expose to make customizing your admin easier.

**Comment by ShaunSpringer** [comment]
I mostly was focused on colors, font weight, and font names. (we use a light font for most of our typography)

**Comment by nhunzaker** [comment]
I've replaced all instances of font weights with font variables. I've also updated the customization doc to include our font variables:

https://github.com/vigetlabs/active_material/blob/master/docs/customization.md#font-variables

On a component-by-component basis, a lot of variables are defined at the top of each file to allow for overides:
https://github.com/vigetlabs/active_material/tree/master/app/assets/stylesheets/active_material/components
