### ISSUE TITLE
Date select contrast is low

### ISSUE THREAD

**Issue by nhunzaker** [dkniffin/active_material#3]
![screen shot 2015-04-30 at 12 26 04 pm](https://cloud.githubusercontent.com/assets/590904/7417473/463a66a0-ef34-11e4-8992-53bf161807cb.png)

**Comment by dkniffin** [comment]
@nhunzaker What type of input is this? I can't reproduce it

**Comment by nhunzaker** [comment]
@dkniffin great question. It's been so long, and I do not remember the specific active-admin configuration to generate this.

It's possible that this code was transitioned over to the native date picker a while ago.

**Comment by dkniffin** [comment]
Okay. I'll close this then. If anyone sees it again, I can reopen it.
