### ISSUE TITLE
fix link in customization guide

### ISSUE THREAD

**Issue by krtschmr** [dkniffin/active_material#36]
https://github.com/krtschmr/active_material/commit/d801a4fb800cd801e0405063e44099dd7fe4e982

no idea why i cant make a pullrequest of this

**Comment by dkniffin** [comment]
I've fixed that here: https://github.com/dkniffin/active_material/commit/e91faafcb016477637330ea593673cd521c60aa9 I used a path, in case the repo url changes (again)
