### ISSUE TITLE
Remove connection to Google servers

### ISSUE THREAD

**Issue by omitter** [dkniffin/active_material#48]
I was pretty annoyed when I realized that my browser tried to access Google servers after installing this theme. Please remove the respective lines in `app/assets/javascripts/active_material/fonts.js`, and add a note that the user can add those links himself or better yet, offer the font-file through their own server. Thanks for your consideration.

**Comment by nhunzaker** [comment]
Hmmm. This was easy to integrate when we first did this, but we should self host these fonts. Thanks for pointing it out!
