### ISSUE TITLE
Per page dropdown style is not implemented

### ISSUE THREAD

**Issue by vhermecz** [dkniffin/active_material#76]
Theme does not support the class: pagination_per_page when multiple values are provided in config.per_page. E.g.:

	ActiveAdmin.register Project do
	  menu priority: 2
	  config.per_page = [100, 1000]

![image](https://user-images.githubusercontent.com/214635/91102800-30ed4780-e66a-11ea-88c5-35be635a5284.png)

The screenshot tells, that the dropdown is not Material themed, and the whole per-page construct is placed into a separate line from the pagination control.

Using:
- ruby 2.5.1
- rails 5.2.3
- activeadmin 2.7.0
- activeadmin_addons 1.7.1

**Comment by irmela** [comment]
This should be fixed by #77
