### ISSUE TITLE
Unable to change menu orientation to left hand side

### ISSUE THREAD

**Issue by mikewronski** [dkniffin/active_material#86]
Is there a setting or option to customize where the menu is rendered? I would like it rendered on the left hand side as a collapsable menu, what customizations are necessary here?

**Comment by dkniffin** [comment]
@mikewronski Nothing like that exists currently. That would involve a significant change to the CSS (and maybe HTML) for the header. I think that's outside the scope of this extension at the moment. There is at least one similar theme that does have a sidebar navigation [here](https://github.com/paladini/activeadmin-themes). Maybe that will work for you?
